import withPrivateRoute from "@/hoc/withPrivateRoute";
import Layout from "componets/Layouts";
import Head from "next/head";
import toast, { Toaster } from "react-hot-toast";

const Home = () => {
  return (
    <>
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
          rel="stylesheet"
        />
        <title>E-sign</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        
      </Layout>
    </>
  );
};

export default withPrivateRoute(Home);
